CREATE TABLE IF NOT EXISTS tblClient (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ClientName VARCHAR(30) NOT NULL,
	Password VARCHAR(30) NOT NULL,
	DateCreated TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tblCustomer (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ClientID VARCHAR(30) NOT NULL,
	CustomerName VARCHAR(30) NOT NULL,
	PhoneNumber VARCHAR(30) NOT NULL,
	LoanAmount INT NOT NULL,
	LoanPeriod INT NULL,
	LoanTypeID  INT NOT NULL,
	DateCreated TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tblLoanType (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS tblUser (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	UserName VARCHAR(30) NOT NULL,
	Password VARCHAR(30) NOT NULL,
	UserTypeID INT(6) NOT NULL,
	DateCreated TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tblUserType (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(30) NOT NULL
);